### ISSUE TITLE
Compatibility With Fabric

### ISSUE THREAD

**Issue by xavieerx** [LambdAurora/AurorasDecorations#26]
Is this exclusively only on quilt or can I somehow use it on fabric?
I can't use quilt due to better nether having a couple of errors with it

**Comment by Oliver-makes-code** [comment]
No this is not compatible with fabric. If you're having issues with BetterNether then you should bring it up to the mod authors

**Comment by LambdAurora** [comment]
Oh forgot this was opened, this is Quilt-only for the foreseeable future.

This mod literally breaks with Fabric since 1.18.2 and I am not interested into trying to patch Fabric's internals by hand, while at Quilt I have support for what this mod attempts to achieve.

So far lot of internals of this mod managed to get simplified thanks to Quilt's APIs. 

To sum up this mod's loader compat:
 - Quilt has support for most of what this mod wants to do
 - Fabric is possible but requires patching which is honestly a pain and for a mod that I make for comfort it's definitely not great.
 - Forge literally has core-design APIs that prevent the mod's own design to ever work on their platform.
